local _, L = ...;
if GetLocale() == "ptBR" then
	L.L["%s (%s) by %s"] = "%s (%s) por %s"
	L.L["Add"] = "Adicionar"
	L.L["Close"] = "Fechar"
	L.L["config"] = "config"
	L.L["Config"] = "Configuração"
	L.L["Copy the export string to share or save it."] = "Copie a string de exportação para compartilhar ou salvar."
	L.L["Delete"] = "Excluir"
	L.L["ERROR"] = "ERRO"
	L.L["Export"] = "Exportar"
	L.L["help"] = "ajuda"
	L.L["Import"] = "Importar"
	L.L["Macro length > 255 chars."] = "Macro com mais de 255 caracteres."
	L.L["New #hash on the left, export string above."] = "Novo #hash à esquerda, string de exportação acima."
	L.L["New"] = "Novo"
	L.L["Please edit source macro."] = "Edite a macro de origem."
	L.L["Post"] = "Postar"
	L.L["Print this help."] = "Mostrar esta ajuda."
	L.L["Rename"] = "Renomear"
	L.L["Toy Box"] = "Brinquedos"
	L.L["Update macro."] = "Atualizar macro."
	L.L["update"] = "atualizar"
end