local _, L = ...;
if GetLocale() == "deDE" then
	L.L["%s (%s) by %s"] = "%s (%s) von %s"
	L.L["Add"] = "Hinzufügen"
	L.L["Close"] = "Schließen"
	L.L["config"] = "konfig"
	L.L["Config"] = "Konfiguration"
	L.L["Copy the export string to share or save it."] = "Kopiere den Export-String, um ihn zu teilen oder zu speichern."
	L.L["Delete"] = "Löschen"
	L.L["ERROR"] = "FEHLER"
	L.L["Export"] = "Exportieren"
	L.L["help"] = "hilfe"
	L.L["Import"] = "Importieren"
	L.L["Macro length > 255 chars."] = "Makro ist länger als 255 Zeichen."
	L.L["New #hash on the left, export string above."] = "Neuer #Hash links, Export-String oben."
	L.L["New"] = "Neu"
	L.L["Please edit source macro."] = "Bitte Quellmakro bearbeiten."
	L.L["Post"] = "Senden"
	L.L["Print this help."] = "Diese Hilfe anzeigen."
	L.L["Rename"] = "Umbenennen"
	L.L["Toy Box"] = "Spielzeugkiste"
	L.L["Update macro."] = "Makro aktualisieren."
	L.L["update"] = "aktualisieren"
end