local _, L = ...;
if GetLocale() == "frFR" then
	L.L["%s (%s) by %s"] = "%s (%s) par %s"
	L.L["Add"] = "Ajouter"
	L.L["Close"] = "Fermer"
	L.L["config"] = "config"
	L.L["Config"] = "Configuration"
	L.L["Copy the export string to share or save it."] = "Copiez la chaîne d’exportation pour la partager ou la sauvegarder."
	L.L["Delete"] = "Supprimer"
	L.L["ERROR"] = "ERREUR"
	L.L["Export"] = "Exporter"
	L.L["help"] = "aide"
	L.L["Import"] = "Importer"
	L.L["Macro length > 255 chars."] = "La macro dépasse 255 caractères."
	L.L["New #hash on the left, export string above."] = "Nouveau #hash à gauche, chaîne d’exportation en haut."
	L.L["New"] = "Nouveau"
	L.L["Please edit source macro."] = "Veuillez modifier la macro source."
	L.L["Post"] = "Publier"
	L.L["Print this help."] = "Afficher cette aide."
	L.L["Rename"] = "Renommer"
	L.L["Toy Box"] = "Coffre à jouets"
	L.L["Update macro."] = "Mettre à jour la macro."
	L.L["update"] = "mise à jour"
end