local _, L = ...;
if GetLocale() == "ruRU" then
	L.L["%s (%s) by %s"] = "%s (%s), автор: %s"
	L.L["Add"] = "Добавить"
	L.L["Close"] = "Закрыть"
	L.L["config"] = "настройка"
	L.L["Config"] = "Настройка"
	L.L["Copy the export string to share or save it."] = "Скопируйте строку экспорта, чтобы поделиться или сохранить её."
	L.L["Delete"] = "Удалить"
	L.L["ERROR"] = "ОШИБКА"
	L.L["Export"] = "Экспорт"
	L.L["help"] = "помощь"
	L.L["Import"] = "Импорт"
	L.L["Macro length > 255 chars."] = "Длина макроса превышает 255 символов."
	L.L["New #hash on the left, export string above."] = "Новый #хэш слева, строка экспорта сверху."
	L.L["New"] = "Новый"
	L.L["Please edit source macro."] = "Пожалуйста, отредактируйте исходный макрос."
	L.L["Post"] = "Опубликовать"
	L.L["Print this help."] = "Показать справку."
	L.L["Rename"] = "Переименовать"
	L.L["Toy Box"] = "Игрушки"
	L.L["Update macro."] = "Обновить макрос."
	L.L["update"] = "обновить"
end