local _, L = ...;
if GetLocale() == "itIT" then
	L.L["%s (%s) by %s"] = "%s (%s) di %s"
	L.L["Add"] = "Aggiungi"
	L.L["Close"] = "Chiudi"
	L.L["config"] = "config"
	L.L["Config"] = "Configurazione"
	L.L["Copy the export string to share or save it."] = "Copia la stringa di esportazione per condividerla o salvarla."
	L.L["Delete"] = "Elimina"
	L.L["ERROR"] = "ERRORE"
	L.L["Export"] = "Esporta"
	L.L["help"] = "aiuto"
	L.L["Import"] = "Importa"
	L.L["Macro length > 255 chars."] = "La macro supera i 255 caratteri."
	L.L["New #hash on the left, export string above."] = "Nuovo #hash a sinistra, stringa di esportazione sopra."
	L.L["New"] = "Nuovo"
	L.L["Please edit source macro."] = "Modifica la macro sorgente."
	L.L["Post"] = "Invia"
	L.L["Print this help."] = "Mostra questo aiuto."
	L.L["Rename"] = "Rinomina"
	L.L["Toy Box"] = "Giocattoli"
	L.L["Update macro."] = "Aggiorna la macro."
	L.L["update"] = "aggiorna"
end