local _, L = ...;
if GetLocale() == "esES" or GetLocale() == "esMX" then
    L.L["%s (%s) by %s"] = "%s (%s) por %s"
    L.L["Print this help."] = "Imprime esta ayuda."
    L.L["help"] = "ayuda"
    L.L["name"] = "nombre"

    L.L["WARNING"] = "AVISO"
    L.L["ERROR"] = "ERROR"
    L.L["There is no #HS in the %s macro."] = "No hay #HS en el macro %s."
    L.L["Macro length > 255 chars."] = "Longitud de macro > 255 caracteres."
    L.L["Please edit source macro."] = "Edite el macro fuente."
    L.L["<is not set>"] = "<no está configurado>"
    L.L["Items for mod: %s"] = "Artículos para mod: %s"
    L.L["No items for mod: %s"] = "No hay artículos para el mod: %s"
    L.L["Modifier list:"] = "Lista de modificadores:"
    L.L["Please set macro name to update."] = "Configure el nombre del macro para actualizar."
    L.L["update"] = "actualizar"
    L.L["Update macro."] = "Actualizar macro."
    L.L["add"] = "añadir"
    L.L["<mods>"] = "<mods>"
    L.L["<link>"] = "<enlace>"
    L.L["Add or list toys for a modifier"] = "Agregar o enumerar juguetes para un modificador"
    L.L["remove"] = "eliminar"
    L.L["Remove toy from a modifier"] = "Eliminar juguete de un modificador"
    L.L["mods"] = "mods"
    L.L["List known modifers"] = "Lista de modificadores conocidos"
    L.L["List toys for a modifier"] = "Enumerar juguetes para un modificador"
end
