local _, L = ...;
if GetLocale() == "esES" or GetLocale() == "esMX" then
	L.L["%s (%s) by %s"] = "%s (%s) por %s"
	L.L["Add"] = "Agregar"
	L.L["Close"] = "Cerrar"
	L.L["config"] = "config"
	L.L["Config"] = "Configuración"
	L.L["Copy the export string to share or save it."] = "Copia la cadena de exportación para compartirla o guardarla."
	L.L["Delete"] = "Eliminar"
	L.L["ERROR"] = "ERROR"
	L.L["Export"] = "Exportar"
	L.L["help"] = "ayuda"
	L.L["Import"] = "Importar"
	L.L["Macro length > 255 chars."] = "La macro excede 255 caracteres."
	L.L["New #hash on the left, export string above."] = "Nuevo #hash a la izquierda, cadena de exportación arriba."
	L.L["New"] = "Nuevo"
	L.L["Please edit source macro."] = "Por favor edita la macro de origen."
	L.L["Post"] = "Publicar"
	L.L["Print this help."] = "Mostrar esta ayuda."
	L.L["Rename"] = "Renombrar"
	L.L["Toy Box"] = "Caja de juguetes"
	L.L["Update macro."] = "Actualizar macro."
	L.L["update"] = "actualizar"
end