local _, L = ...;
if GetLocale() == "ptBR" then
    L.L["%s (%s) by %s"] = "%s (%s) por %s"
    L.L["Print this help."] = "Imprimir esta ajuda."
    L.L["help"] = "ajuda"
    L.L["name"] = "nome"

    L.L["WARNING"] = "AVISO"
    L.L["ERROR"] = "ERRO"
    L.L["There is no #HS in the %s macro."] = "Não há #HS na macro %s."
    L.L["Macro length > 255 chars."] = "Comprimento da macro > 255 caracteres."
    L.L["Please edit source macro."] = "Edite a macro de origem."
    L.L["<is not set>"] = "<não está definido>"
    L.L["Items for mod: %s"] = "Itens para mod: %s"
    L.L["No items for mod: %s"] = "Nenhum item para mod: %s"
    L.L["Modifier list:"] = "Lista de modificadores:"
    L.L["Please set macro name to update."] = "Defina o nome da macro para atualização."
    L.L["update"] = "atualizar"
    L.L["Update macro."] = "Atualizar macro."
    L.L["add"] = "adicionar"
    L.L["<mods>"] = "<mods>"
    L.L["<link>"] = "<link>"
    L.L["Add or list toys for a modifier"] = "Adicionar ou listar brinquedos para um modificador"
    L.L["remove"] = "remover"
    L.L["Remove toy from a modifier"] = "Remover brinquedo de um modificador"
    L.L["mods"] = "mods"
    L.L["List known modifers"] = "Listar modificadores conhecidos"
end
